version: '3.8' 
services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:3000/api

  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
    ports:
      - "3000:3000"         
    environment:
      - APP_HOSTNAME: 0.0.0.0
      - APP_PORT: 3000

networks:
  default:
    driver: bridge