services:
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - API_URL=http://192.168.50.109:3000 # replace me with the ip address of the backend. It should be always port 3000
    networks:
      - todo-network

  backend:
    build:
      context: ./backend   
      dockerfile: Dockerfile
    ports:
      - "3000:3000"         
    environment:
      - APP_HOSTNAME=0.0.0.0
      - APP_PORT=3000
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge